### ISSUE TITLE
Add fields to 'iDEAL transacties' ('idealDetail') user record

### ISSUE THREAD

**Issue by sandrab** [circuitnederland/registrationform#12]
From Roder:
"Every time Cyclos transfers "circulaire euro's" initiated by a molly payment, Cyclos should create a user record for this. First this will only be used by the registration form, but later this should also be used for the topup function. In this user record all payment information available in molly should be saved. Also the transfer id or tranfer number should be stored in the user record (so that both are linked). This already works, but the cyclos transaction id is not included and the mollie payment id should be included. Please check if there is other information that could be saved. To make this work first all checks should be done and the payment should be processed in Cyclos and only in the last stage this record should be created."

Which fields to add:
- The Mollie paymentId: to add this in activateUserCheckPayment, move the line that instantiates the local paymentId variable (`def paymentId = usr.payment_id`) out of the if-statement checking the Betaald field. Then, at the bottom of the script use this variable.
- The Mollie amount (decimal).
- The Mollie field 'method' (string): for now, this will always be 'ideal'.
- The Cyclos transactionnumber: activateUserCheckPayment should fill this with the transactionnumber of the transaction 'Aankoop Units' that is created when the user is activated.
- 'paid' (boolean): This field will be mainly used by the topup functionality, but it is good to anticipate on this. By default the 'paid' field will have the value 'true' for payments from the registration form because in the registration procedure the record is created after the payment is done succesfuly.
- 'source': (single select field): option values 'registration' and 'topup'.

What to do to add fields:
- Add fields manually to the user recordtype ((Systeem > [Systeemconfiguratie] Recordtypen > 'iDEAL transacties' (Interne naam: 'idealDetail')). This manual action should be stored in the deployment list.
- Change the 'mollie' library script: add the fields in the IdealDetailRecord class, its constructor and its create() method.
- Change the 'activateUserCheckPayment' extension script: add the new fields in its step 11 at the bottom of the script, where it calls idealRecord.create().
Update: the step 11 storing the bank account info in a user record will probably move to a separate function processPayments() (going in a library script somewhere), along with the steps to create the transactions. The reason is that the new custom operation script 'Handmatige overboeking toevoegen' can then also call this same processPayments() function. See #23.

**Comment by rmvanarkel** [comment]
The Cyclos transactionnumber > Please use a so called linked entity for this of type transaction.

**Comment by sandrab** [comment]
@rmvanarkel : I am using paymentVO.transactionNumber now. Is that indeed what you mean with 'use a so called linked entity'? See https://github.com/circuitnederland/registrationform/commit/f31ed8f283465982c9fdaece07c12bed07e49cec#diff-2befb577a22dc83879bf6fff429c0ecaR405

**Comment by rmvanarkel** [comment]
A link entity is a custom field type. So if you go to the user record System > Record Types > Open record > (Fields) > New > Data type > Linked entity. You can past here just the value of the transaction number or id and it will automatically create a hyperlink then to the transaction when people look at the user record.

**Comment by sandrab** [comment]
The userrecord text field transactionnumber is now replaced by a field transaction of type 'linked entity'.
