### ISSUE TITLE
Change mollie description message

### ISSUE THREAD

**Issue by sandrab** [circuitnederland/registrationform#30]
The description in the Mollie screen gets truncated to ca 35 characters. This only happens in the real mollie environment, not in the testmode. To work around this limitation, we might change the description from:
`Jaarlijkse contributie (€#lidmaatschapsbijdrage#) + startsaldo (€#aankoop_saldo#) voor gebruiker #username#.`
to:
`Inschrijfkosten Circuit Nederland`
This description is a scriptparameter in the mollie library script. So it can be changed in mollie.properties (and in the comments in mollie.groovy) and manually copied to the scriptparameters field in Cyclos.

**Comment by rmvanarkel** [comment]
For me the example seems a bit strange. And honestly it is also incorrect. It is also not only the yearly fee it is also the amount of units purchased. Maybe this would do Inschrijfkosten circuitnederland.nl (voor #username#)
