### ISSUE TITLE
Change maximum 'Aankoop saldo' to 10.000

### ISSUE THREAD

**Issue by sandrab** [circuitnederland/registrationform#8]
Change the maximum amount that can be filled in as 'Aankoop saldo' from 50.000 to 10.000. This way the total transaction (which is the 'aankoop saldo' plus the 'lidmaatschapsbijdrage') never exceeds any maximum within Mollie and stays within decent limits.

Also add a server-side (PHP) validation for this maximum, so the clientside javascript validation is not the only check (it can be circumvented if someone wants to do bad things).

**Comment by rmvanarkel** [comment]
Please check also #7 when fixing.

**Comment by sandrab** [comment]
For other profilefields the validation is done a) client-side and b) in Cyclos. For example the iban and kvknummer fields have min/max settings in Cyclos. I would think it is logical to do the validation of the aankoop_saldo field in a similar way. So not adding server-side PHP validation, but adding server-side validation by filling in min/max settings in the profilefield in Cyclos.

@rmvanarkel : Do you agree or would there be a specific reason to do the validation of the aankoop saldo in PHP instead of in Cyclos (next to clientside valdition of course)?
